jobs:
  check-proxies:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <--- THIS gives the workflow permission to push
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pysocks

      - name: Run proxy checker
        run: python proxy_checker.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Active_Proxies.json
          git commit -m "Update active proxies [skip ci]" || echo "No changes"
          git push
