name: Proxy Checker

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:         # manual run

jobs:
  check-proxies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests PySocks

      - name: Run proxy checker
        run: python proxy_checker.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Active_Proxies.txt
          git commit -m "Update active proxies [skip ci]" || echo "No changes"
          git push
